### ISSUE TITLE
gazebo_mecanum_plugins_vel.h

### ISSUE THREAD

**Issue by LdZengduke** [qaz9517532846/gazebo_mecanum_plugins#1]
Hi ！When I catkin_make this package, the terminal prompts me that there is no"gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h", I didn’t find this file in the INCLUDE price folder, please tell me what is going on？

**Comment by qaz9517532846** [comment]
Not found "gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h" because CMakeLists.txt and package.xml do not add relative message add_dependencies using kinetic and melodic, I already updated CMakeLists.txt and package.xml. you can rebuild it after download it again. if you have any problem and contact me.
Thank you.

**Comment by LdZengduke** [comment]
Thank you so much for your reply, I have rebuilt the package following your words, while the above problems still exist. No such header files can be found, I have noticed your modification in the CMakeLists.txt and package.xml. I think the question might be more ‘.h’ in the INCLUDE.
A big thanks again!

发件人: Zhe-Ming, Zhang
发送时间: 2021年8月6日 3:06
收件人: qaz9517532846/gazebo_mecanum_plugins
抄送: LdZengduke; Author
主题: Re: [qaz9517532846/gazebo_mecanum_plugins]gazebo_mecanum_plugins_vel.h (#1)

not found gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h because CMakeLists.txt and package.xml do not add relative message add_dependencies using kinetic and melodic, I already updated CMakeLists.txt and package.xml. you can rebuild after download it again. if you have any problem and contact me.
Thank you.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by qaz9517532846** [comment]
Which ROS version are you using? I tested to build package success after fixing CMakeLists.txt and package.xml under ROS kinetic. Please show me the all build log.
Thank you.

**Comment by LdZengduke** [comment]
My version is the same as yours, it's also ROS kinetic. 
Attached please find the build log.
Thank you a lot!

发件人: Zhe-Ming, Zhang
发送时间: 2021年8月6日 12:31
收件人: qaz9517532846/gazebo_mecanum_plugins
抄送: LdZengduke; Author
主题: Re: [qaz9517532846/gazebo_mecanum_plugins]gazebo_mecanum_plugins_vel.h (#1)

Which ROS version are you using? I tested to build package success after fixing CMakeLists.txt and package.xml under ROS kinetic. Please show me the all build log.
Thank you.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.


/home/zld/mecanum_ws/build/gazebo_mecanum_plugins/setup_custom_pythonpath.sh: 5: exec: /home/zld/mecanum_ws/src/gazebo_mecanum_plugins/cfg/gazebo_ros_mecanum_pid.cfg: Permission denied
gazebo_mecanum_plugins/CMakeFiles/gazebo_mecanum_plugins_gencfg.dir/build.make:63: recipe for target '/home/zld/mecanum_ws/devel/include/gazebo_mecanum_plugins/gazebo_ros_mecanum_pidConfig.h' failed
make[2]: *** [/home/zld/mecanum_ws/devel/include/gazebo_mecanum_plugins/gazebo_ros_mecanum_pidConfig.h] Error 126
CMakeFiles/Makefile2:661: recipe for target 'gazebo_mecanum_plugins/CMakeFiles/gazebo_mecanum_plugins_gencfg.dir/all' failed
make[1]: *** [gazebo_mecanum_plugins/CMakeFiles/gazebo_mecanum_plugins_gencfg.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[  5%] Built target _gazebo_mecanum_plugins_generate_messages_check_deps_gazebo_mecanum_plugins_pid
[  5%] Built target _gazebo_mecanum_plugins_generate_messages_check_deps_gazebo_mecanum_plugins_vel
[ 10%] Building CXX object gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/src/gazebo_ros_mecanum_pid_drive.cpp.o
[ 15%] Building CXX object gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_diff_drive.dir/src/gazebo_ros_mecanum_diff_drive.cpp.o
In file included from /home/zld/mecanum_ws/src/gazebo_mecanum_plugins/src/gazebo_ros_mecanum_pid_drive.cpp:1:0:
/home/zld/mecanum_ws/src/gazebo_mecanum_plugins/include/gazebo_mecanum_plugins/gazebo_ros_mecanum_diff_drive.h:25:63: fatal error: gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h: 没有那个文件或目录
In file included from /home/zld/mecanum_ws/src/gazebo_mecanum_plugins/src/gazebo_ros_mecanum_diff_drive.cpp:1:0:
/home/zld/mecanum_ws/src/gazebo_mecanum_plugins/include/gazebo_mecanum_plugins/gazebo_ros_mecanum_diff_drive.h:25:63: fatal error: gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h: 没有那个文件或目录
compilation terminated.
compilation terminated.
gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/build.make:62: recipe for target 'gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/src/gazebo_ros_mecanum_pid_drive.cpp.o' failed
make[2]: *** [gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/src/gazebo_ros_mecanum_pid_drive.cpp.o] Error 1
gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_diff_drive.dir/build.make:62: recipe for target 'gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_diff_drive.dir/src/gazebo_ros_mecanum_diff_drive.cpp.o' failed
make[2]: *** [gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_diff_drive.dir/src/gazebo_ros_mecanum_diff_drive.cpp.o] Error 1
CMakeFiles/Makefile2:489: recipe for target 'gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/all' failed
make[1]: *** [gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/all] Error 2
CMakeFiles/Makefile2:828: recipe for target 'gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_diff_drive.dir/all' failed
make[1]: *** [gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_diff_drive.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by qaz9517532846** [comment]
I discovered dynamic_reconfigure build problem:

 /home/zld/mecanum_ws/build/gazebo_mecanum_plugins/setup_custom_pythonpath.sh: 5: exec: /home/zld/mecanum_ws/src/gazebo_mecanum_plugins/cfg/gazebo_ros_mecanum_pid.cfg: Permission denied
gazebo_mecanum_plugins/CMakeFiles/gazebo_mecanum_plugins_gencfg.dir/build.make:63: recipe for target '/home/zld/mecanum_ws/devel/include/gazebo_mecanum_plugins/gazebo_ros_mecanum_pidConfig.h' failed_

msg and cfg not generated header file because gazebo_ros_mecanum_pid.cfg file not set to active file, gazebo_mecanum_plugins package will not do build while gazebo_ros_mecanum_pid.cfg build failed and not found it problem.

Please follow me run command on terminal:

$ roscd gazebo_mecanum_plugins/cfg

$ chmod a+x gazebo_ros_mecanum_pid.cfg

$ cd /home/zld/mecanum_ws

$ rm -r devel && rm -r build

$ catkin_make

$ source ~/.bashrc

**Comment by LdZengduke** [comment]
Thank you very much! I have successfully solved the problem according to your tips!
Have a nice day!


发件人: Zhe-Ming, Zhang
发送时间: 2021年8月6日 17:40
收件人: qaz9517532846/gazebo_mecanum_plugins
抄送: LdZengduke; Author
主题: Re: [qaz9517532846/gazebo_mecanum_plugins]gazebo_mecanum_plugins_vel.h (#1)

I discovered dynamic_reconfigure build problem:
/home/zld/mecanum_ws/build/gazebo_mecanum_plugins/setup_custom_pythonpath.sh: 5: exec: /home/zld/mecanum_ws/src/gazebo_mecanum_plugins/cfg/gazebo_ros_mecanum_pid.cfg: Permission denied
gazebo_mecanum_plugins/CMakeFiles/gazebo_mecanum_plugins_gencfg.dir/build.make:63: recipe for target '/home/zld/mecanum_ws/devel/include/gazebo_mecanum_plugins/gazebo_ros_mecanum_pidConfig.h' failed_
msg and cfg not generated header file because gazebo_ros_mecanum_pid.cfg file not set to active file, gazebo_mecanum_plugins package will not do build while gazebo_ros_mecanum_pid.cfg build failed and not found it problem.
Please follow me run command on terminal:
$ roscd gazebo_mecanum_plugins/cfg
$ chmod a+x gazebo_ros_mecanum_pid.cfg
$ cd /home/zld/mecanum_ws
$ rm -r devel && rm -r build
$ catkin_make
$ source ~/.bashrc
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
