### ISSUE TITLE
problemas con el plugins

### ISSUE THREAD

**Issue by SebastianA14** [qaz9517532846/gazebo_mecanum_plugins#3]
Hello, I have a problem when cloning gazebo_mecanum_plugins and doing catkin_make tells me the following
Building CXX object ira_laser_tools/CMakeFiles/laserscan_virtualizer.dir/src/laserscan_virtualizer.cpp.o
In file included from /home/seb/pp/src/gazebo_mecanum_plugins/src/gazebo_ros_mecanum_pid_drive.cpp:1:
/home/seb/pp/src/gazebo_mecanum_plugins/include/gazebo_mecanum_plugins/gazebo_ros_mecanum_drive.h:23:10: fatal error: gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h: No existe el archivo o el directorio
23 | #include <gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h>
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from /home/seb/pp/src/gazebo_mecanum_plugins/src/gazebo_ros_mecanum_drive.cpp:1:
/home/seb/pp/src/gazebo_mecanum_plugins/include/gazebo_mecanum_plugins/gazebo_ros_mecanum_drive.h:23:10: fatal error: gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h: No existe el archivo o el directorio
23 | #include <gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h>
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/build.make:63: gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/src/gazebo_ros_mecanum_pid_drive.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2965: gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/all] Error 2
make[1]: *** Se espera a que terminen otras tareas....
make[2]: *** [gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_drive.dir/build.make:63: gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_drive.dir/src/gazebo_ros_mecanum_drive.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2992: gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_drive.dir/all] Error 2

since the file gazebo_mecanum_plugins_vel.h
does not exist in gazebo_mecanum_plugins folder and is called in other scripts like gazebo_ros_mecanum_drive.h

**Comment by qaz9517532846** [comment]
> Hello, I have a problem when cloning gazebo_mecanum_plugins and doing catkin_make tells me the following Building CXX object ira_laser_tools/CMakeFiles/laserscan_virtualizer.dir/src/laserscan_virtualizer.cpp.o In file included from /home/seb/pp/src/gazebo_mecanum_plugins/src/gazebo_ros_mecanum_pid_drive.cpp:1: /home/seb/pp/src/gazebo_mecanum_plugins/include/gazebo_mecanum_plugins/gazebo_ros_mecanum_drive.h:23:10: fatal error: gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h: No existe el archivo o el directorio 23 | #include <gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. In file included from /home/seb/pp/src/gazebo_mecanum_plugins/src/gazebo_ros_mecanum_drive.cpp:1: /home/seb/pp/src/gazebo_mecanum_plugins/include/gazebo_mecanum_plugins/gazebo_ros_mecanum_drive.h:23:10: fatal error: gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h: No existe el archivo o el directorio 23 | #include <gazebo_mecanum_plugins/gazebo_mecanum_plugins_vel.h> | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ compilation terminated. make[2]: *** [gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/build.make:63: gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/src/gazebo_ros_mecanum_pid_drive.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:2965: gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_pid_drive.dir/all] Error 2 make[1]: *** Se espera a que terminen otras tareas.... make[2]: *** [gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_drive.dir/build.make:63: gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_drive.dir/src/gazebo_ros_mecanum_drive.cpp.o] Error 1 make[1]: *** [CMakeFiles/Makefile2:2992: gazebo_mecanum_plugins/CMakeFiles/gazebo_ros_mecanum_drive.dir/all] Error 2
> 
> since the file gazebo_mecanum_plugins_vel.h does not exist in gazebo_mecanum_plugins folder and is called in other scripts like gazebo_ros_mecanum_drive.h

CmakeList.txt not added dependencies message and service cause too compiler error, I updated CmakeList.txt, you comfirm it please.
